<?php

namespace App\Filament\Resources\Students\Pages;

use App\Filament\Resources\Students\StudentResource;
use App\Models\Alumni;
use App\Models\SiswaKeluar;
use App\Models\Student;
use Filament\Actions\DeleteAction;
use Filament\Resources\Pages\EditRecord;

class EditStudent extends EditRecord
{
    protected static string $resource = StudentResource::class;

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }

    protected function getHeaderActions(): array
    {
        return [
            DeleteAction::make()
                ->after(function () {
                    $this->dispatch('swal:success', [
                        'title' => 'Data Dihapus!',
                        'text' => 'Data siswa berhasil dihapus dari database.',
                    ]);
                }),
        ];
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        // Store additional fields for processing in afterSave
        // Lulus fields
        $this->tahunLulus = $data['tahun_lulus'] ?? null;

        // Mutasi Keluar fields
        $this->tanggalKeluar = $data['tanggal_keluar'] ?? null;
        $this->alasanKeluar = $data['alasan_keluar'] ?? null;
        $this->sekolahTujuan = $data['sekolah_tujuan'] ?? null;
        $this->nomorDokumenEmis = $data['nomor_dokumen_emis'] ?? null;

        // Remove non-database fields
        unset(
            $data['tahun_lulus'],
            $data['tanggal_keluar'],
            $data['alasan_keluar'],
            $data['sekolah_tujuan'],
            $data['nomor_dokumen_emis']
        );

        return $data;
    }

    protected function afterSave(): void
    {
        $student = $this->record;

        // Handle status change to Lulus
        if ($student->status === Student::STATUS_LULUS) {
            // Check if already exists in alumni
            $existingAlumni = Alumni::where('student_id', $student->id)->first();

            if (!$existingAlumni) {
                Alumni::create([
                    'student_id' => $student->id,
                    'photo' => $student->photo,
                    'nama_lengkap' => $student->nama_lengkap,
                    'nis_lokal' => $student->nis_lokal,
                    'nisn' => $student->nisn,
                    'nik' => $student->nik,
                    'gender' => $student->gender,
                    'kelas_terakhir' => $student->kelas,
                    'tempat_lahir' => $student->tempat_lahir,
                    'tanggal_lahir' => $student->tanggal_lahir,
                    'nama_ibu' => $student->nama_ibu,
                    'nama_ayah' => $student->nama_ayah,
                    'tahun_lulus' => $this->tahunLulus ?? date('Y'),
                    'alamat' => $student->alamat_kk,
                    'nomor_mobile' => $student->nomor_mobile,
                ]);

                // Set student as inactive
                $student->update(['is_active' => false]);

                $this->dispatch('swal:success', [
                    'title' => 'Status Diperbarui!',
                    'text' => 'Data siswa berhasil diperbarui dan dipindahkan ke data Alumni.',
                ]);
                return;
            }
        }

        // Handle status change to Mutasi Keluar
        if ($student->status === Student::STATUS_MUTASI_KELUAR) {
            // Check if already exists in siswa_keluar
            $existingSiswaKeluar = SiswaKeluar::where('student_id', $student->id)->first();

            if (!$existingSiswaKeluar) {
                SiswaKeluar::create([
                    'student_id' => $student->id,
                    'photo' => $student->photo,
                    'nama_lengkap' => $student->nama_lengkap,
                    'nis_lokal' => $student->nis_lokal,
                    'nisn' => $student->nisn,
                    'nik' => $student->nik,
                    'gender' => $student->gender,
                    'kelas_terakhir' => $student->kelas,
                    'tempat_lahir' => $student->tempat_lahir,
                    'tanggal_lahir' => $student->tanggal_lahir,
                    'nama_ibu' => $student->nama_ibu,
                    'nama_ayah' => $student->nama_ayah,
                    'nomor_mobile' => $student->nomor_mobile,
                    'alamat' => $student->alamat_kk,
                    'tanggal_keluar' => $this->tanggalKeluar ?? now(),
                    'alasan_keluar' => $this->alasanKeluar,
                    'sekolah_tujuan' => $this->sekolahTujuan,
                    // nomor_surat is auto-generated by SiswaKeluar model
                    'nomor_dokumen_emis' => $this->nomorDokumenEmis,
                ]);

                // Set student as inactive
                $student->update(['is_active' => false]);

                $this->dispatch('swal:success', [
                    'title' => 'Status Diperbarui!',
                    'text' => 'Data siswa berhasil diperbarui dan dipindahkan ke data Siswa Keluar.',
                ]);
                return;
            }
        }

        $this->dispatch('swal:success', [
            'title' => 'Data Diperbarui!',
            'text' => 'Data siswa berhasil diperbarui.',
        ]);
    }
}


